// Mocks generated by Mockito 5.4.6 from annotations
// in restaurant_app/test/restaurant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_app/data/api/api_service.dart' as _i3;
import 'package:restaurant_app/data/model/restaurant_result.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRestaurantResult_0 extends _i1.SmartFake
    implements _i2.RestaurantResult {
  _FakeRestaurantResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRestaurant_1 extends _i1.SmartFake implements _i2.Restaurant {
  _FakeRestaurant_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RestaurantResult> list() =>
      (super.noSuchMethod(
            Invocation.method(#list, []),
            returnValue: _i4.Future<_i2.RestaurantResult>.value(
              _FakeRestaurantResult_0(this, Invocation.method(#list, [])),
            ),
          )
          as _i4.Future<_i2.RestaurantResult>);

  @override
  _i4.Future<_i2.Restaurant> getDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDetail, [id]),
            returnValue: _i4.Future<_i2.Restaurant>.value(
              _FakeRestaurant_1(this, Invocation.method(#getDetail, [id])),
            ),
          )
          as _i4.Future<_i2.Restaurant>);
}
